language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-dupe --allow-redirect --white-list wiki.haskell.org,www.goodreads.com,en.wikipedia.org/wiki/John_Gall_(author)
